custombucket = "akshays3dontdelete"
table = "intellipaat"
databasehost = "akshayrds.cfe9zvkzerng.us-west-1.rds.amazonaws.com"
duser = "admin"
dpass = "Akshay123#"
s3database = "intellipaat"
kapp = "http://192.168.2.102:30871/"
